<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gemstone.Configuration" Version="1.0.179" />
    <PackageReference Include="Gemstone.Data" Version="1.0.180" />
    <PackageReference Include="Gemstone.IO" Version="1.0.180" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\openXDA.Model\openXDA.Model.csproj" />
  </ItemGroup>

</Project>
